version: '3.7'

services:
  backend:
    build: ./student-stay
    command: python manage.py migrate --run-syncdb
    command: python manage.py runserver
    ports:
      - 8000:8000
  frontend:
    build : ./frontend
    ports: 
      - 3000:3000  