version: '3.7'

services:
  backend:
    build: ./student-stay
    command: python manage.py migrate --run-syncdb
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
  # frontend:
  #   build : ./frontend
  #   ports: 
  #     - 80:80  
  frontend:
    build : ./frontend
    expose:
      - 3000
    ports:
      - "3000:3000"
    stdin_open: true 
  